apiVersion: v1
kind: Namespace
metadata:
   name: hy
   labels:
     name: hy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: php-apache-hy
  name: php-apache-hy
  namespace: hy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: php-apache-hy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: php-apache-hy
    spec:
      containers:
      - image: registry.cn-shanghai.aliyuncs.com/tvtaqa/hpatest:v30
        imagePullPolicy: IfNotPresent
        name: php-apache-hy
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache-hy
  namespace: hy
spec:
  ports:
  - nodePort: 32215
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: php-apache-hy
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}