---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: copa
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: copa
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: copa
  apiGroup: rbac.authorization.k8s.io